-- MySQL Script generated by MySQL Workbench
-- Tue Jan  6 14:57:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombres` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Correo Institucional` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `idroles` INT NOT NULL,
  `tipo_rol` ENUM('estudiante', 'tutor', 'Director', 'Coordinador', 'comite') NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_roles` (
  `Usuario_idUsuario` INT NOT NULL,
  `roles_idroles` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `roles_idroles`),
  INDEX `fk_Usuario_has_roles_roles1_idx` (`roles_idroles` ASC) VISIBLE,
  INDEX `fk_Usuario_has_roles_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_roles_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_roles_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `mydb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `idEstudiante` INT NOT NULL,
  `semestre` ENUM('Septimo', 'Octavo') NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEstudiante`),
  INDEX `fk_Estudiante_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prerequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prerequisitos` (
  `idPrerequisitos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idPrerequisitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cordinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cordinador` (
  `idCordinador` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCordinador`, `Usuario_idUsuario`),
  INDEX `fk_Cordinador_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Cordinador_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Propuesta_tesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Propuesta_tesis` (
  `idPropuesta_tesis` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(45) NULL,
  `objetivos` TEXT NULL,
  `problematica` TEXT NULL,
  `are_investigacion` VARCHAR(50) NULL,
  `alcance` TEXT NULL,
  `archivo` VARCHAR(255) NULL,
  `fecha_publicacion` DATE NULL,
  `fecha_limite` DATE NULL,
  `estado` ENUM('En Revision', 'Aprobada', 'Rechazada', 'Pendiente') DEFAULT 'Pendiente',
  `seleccionada` TINYINT DEFAULT 0,
  `comentarios_generales` TEXT NULL,
  `Estudiante_idEstudiante` INT NOT NULL,
  PRIMARY KEY (`idPropuesta_tesis`),
  INDEX `fk_Propuesta_tesis_Estudiante1_idx` (`Estudiante_idEstudiante` ASC) VISIBLE,
  CONSTRAINT `fk_Propuesta_tesis_Estudiante1`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `mydb`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tutor` (
  `idtutor` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idtutor`, `Usuario_idUsuario`),
  INDEX `fk_tutor_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tutor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director` (
  `idDirector` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idDirector`, `Usuario_idUsuario`),
  INDEX `fk_Director_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Director_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avance` (
  `idAvance` INT NOT NULL AUTO_INCREMENT,
  `semana` INT NULL,
  `calificacion` DECIMAL(4,2) NULL,
  `contenido` TEXT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_entrega` DATE NULL,
  `fecha_limite` DATE NULL,
  `estado` ENUM('entregado', 'no entregado', 'calificado') NULL,
  `verficacion_revicion` TINYINT NULL,
  `Propuesta_tesis_idPropuesta_tesis` INT NOT NULL,
  `tutor_idtutor` INT NULL,
  PRIMARY KEY (`idAvance`),
  INDEX `fk_Avance_Propuesta1_idx` (`Propuesta_tesis_idPropuesta_tesis` ASC) VISIBLE,
  CONSTRAINT `fk_Avance_Propuesta1`
    FOREIGN KEY (`Propuesta_tesis_idPropuesta_tesis`)
    REFERENCES `mydb`.`Propuesta_tesis` (`idPropuesta_tesis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante_has_Prerequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante_has_Prerequisitos` (
  `Estudiante_idEstudiante` INT NOT NULL,
  `Prerequisitos_idPrerequisitos` INT NOT NULL,
  PRIMARY KEY (`Estudiante_idEstudiante`, `Prerequisitos_idPrerequisitos`),
  INDEX `fk_Estudiante_has_Prerequisitos_Prerequisitos1_idx` (`Prerequisitos_idPrerequisitos` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Prerequisitos_Estudiante1_idx` (`Estudiante_idEstudiante` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Prerequisitos_Estudiante1`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `mydb`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Prerequisitos_Prerequisitos1`
    FOREIGN KEY (`Prerequisitos_idPrerequisitos`)
    REFERENCES `mydb`.`Prerequisitos` (`idPrerequisitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comite`
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `mydb`.`Evaluacion_Propuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evaluacion_Propuesta` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `Propuesta_tesis_idPropuesta_tesis` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `rol_revisor` ENUM('miembro_comite', 'tutor_revisor', 'director_carrera') NULL,
  `comentarios` TEXT NULL,
  `calificacion` DECIMAL(4,2) NULL,
  `fecha_evaluacion` DATE NULL,
  PRIMARY KEY (`idEvaluacion`),
  INDEX `fk_Evaluacion_Propuesta_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Evaluacion_Propuesta_Propuesta1_idx` (`Propuesta_tesis_idPropuesta_tesis` ASC) VISIBLE,
  CONSTRAINT `fk_Evaluacion_Propuesta_Propuesta1`
    FOREIGN KEY (`Propuesta_tesis_idPropuesta_tesis`)
    REFERENCES `mydb`.`Propuesta_tesis` (`idPropuesta_tesis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_Propuesta_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Predefensa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Predefensa` (
  `idPredefensa` INT NOT NULL,
  `fecha` DATE NULL,
  `manual_usuario` VARCHAR(255) NULL,
  `manual_programador` VARCHAR(255) NULL,
  `articulo_cientifico` VARCHAR(255) NULL,
  `calificacion` DECIMAL(4,2) NULL,
  `Propuesta_tesis_idPropuesta_tesis` INT NOT NULL,
  PRIMARY KEY (`idPredefensa`),
  INDEX `fk_Predefensa_Propuesta1_idx` (`Propuesta_tesis_idPropuesta_tesis` ASC) VISIBLE,
  CONSTRAINT `fk_Predefensa_Propuesta1`
    FOREIGN KEY (`Propuesta_tesis_idPropuesta_tesis`)
    REFERENCES `mydb`.`Propuesta_tesis` (`idPropuesta_tesis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Defensa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Defensa` (
  `idDefensa` INT NOT NULL,
  `calificacion` DECIMAL(4,2) NULL,
  `acta_grado` VARCHAR(255) NULL,
  `Propuesta_tesis_idPropuesta_tesis` INT NOT NULL,
  PRIMARY KEY (`idDefensa`),
  INDEX `fk_Defensa_Propuesta1_idx` (`Propuesta_tesis_idPropuesta_tesis` ASC) VISIBLE,
  CONSTRAINT `fk_Defensa_Propuesta1`
    FOREIGN KEY (`Propuesta_tesis_idPropuesta_tesis`)
    REFERENCES `mydb`.`Propuesta_tesis` (`idPropuesta_tesis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
